Recreate project
Alopias-Vulpinus/FreelancePlatform pull request #2
Opened 2021-10-06 10:41 UTC by dimasindro

2021-10-06 10:58 UTC, KirylAkulich1 requested changes
Потом чеку еще)

2021-10-06 10:58 UTC, KirylAkulich1 commented on client/src/pages/AuthPage.js
> +              Войти
Может: лучше все делать на инглише, так выглядит солидно

2021-10-06 10:58 UTC, KirylAkulich1 commented on Procfile
> -web: npm start
куда делся этот файл. Как хостинг понимает, что ему нужно делать?

2021-10-06 10:58 UTC, KirylAkulich1 commented on .idea/vcs.xml
> +  <component name="VcsDirectoryMappings">
шо цэ таке. В игнор

2021-10-06 10:58 UTC, KirylAkulich1 commented on client/README.md
> +### Code Splitting
шо за файл. Думаю, его можно снести

2021-10-06 11:12 UTC, Dzmitry-Bialotski commented on Procfile
> -web: npm start
Скрипт в package.json, а на удаленном на хероку там пару команд с билдом по идее надо прописать

2021-10-06 17:01 UTC, KirylAkulich1 commented on Procfile
> -web: npm start
уверен, просто этот фалик для этого и был придуман

2021-10-09 08:56 UTC, KirylAkulich1 approved these changes

2021-10-09 08:56 UTC, merged